version: 2.1

orbs:
  node: circleci/node@4.1.0 # orb version

jobs:
  test:
    docker:
      - image: cimg/node:14.15.0
        auth:
          username: dmarcogabriel
          password: gabriel@16
    steps:
      - checkout
      - node/install-packages